config/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.views import defaults as default_views
from .views import HomePageView, AboutPageView


urlpatterns = [
    
    # ADMIN
    path('admin/', admin.site.urls),

    # HOMEPAGE
    path('', HomePageView.as_view(), name='home'),

    # BACKEND
    path('', include('unlabel_app.unlabel_backend.urls')),

    # PAGES
    path('about/', AboutPageView.as_view(), name="about"),
    path('contact/', TemplateView.as_view(template_name='pages/contact.html'), name="contact"),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

unlabel_app/unlabel_backend/urls.py
from django.urls import include, path

from .views import ProjectListView, ProjectDetailView

urlpatterns = [

    path('', include(([

        path('projects/', ProjectListView.as_view(), name='projects'),

        path('project/<slug:slug>', ProjectDetailView.as_view(), name='project_detail'),
   
    ], 'unlabel_backend'), namespace='projects')),
]

unlabel_app/unlabel_backend/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.urls import reverse

from .abstract_models import TimeModel

from multiselectfield import MultiSelectField

from cloudinary.models import CloudinaryField

from config.utils.data import SERVICES_CHOICES


@python_2_unicode_compatible
class Project(TimeModel):
    
    title = models.CharField(max_length=255, null=True, blank=False)

    client_name = models.CharField(max_length=255, null=True, blank=True, verbose_name=_('Client Name') )

    cover_image = CloudinaryField('Cover Image', null=True, blank=True)

    description = models.TextField(max_length=1000, null=True, blank=True )

    services = MultiSelectField(max_length=100, choices=SERVICES_CHOICES )

    slug = models.SlugField(_('Slug'), max_length=255, unique=True, blank=True)

    is_active = models.BooleanField(_('Active'), default=True)

    def __str__(self):
        return "{0}: {1}".format(self.title, self.client_name)

    def get_absolute_url(self):
        return reverse('projects:project_detail', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        
        self.full_clean()
        
        super(Project, self).save(*args, **kwargs)

    # Metadata
    class Meta: 
        verbose_name = _('Project')
        verbose_name_plural = _('Projects')


@python_2_unicode_compatible
class ProjectImage(models.Model):

	project = models.ForeignKey(Project, on_delete=models.CASCADE,  null=True, blank=True, verbose_name=_('Project'), related_name='images')
    
	image = CloudinaryField('Image', null=True, blank=True)

	def __str__(self):
		return "Image of {0}".format(self.project)

	# Metadata
	class Meta: 
		verbose_name = _('Project Image')
		verbose_name_plural = _('Project Images')

config/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy

from django.views.generic import TemplateView, ListView

from unlabel_app.unlabel_backend.models import Project


class HomePageView(TemplateView):

    template_name = 'pages/home.html'

    def get_context_data(self, **kwargs):
        kwargs['projects'] = Project.objects.all().order_by('-created')[0:5]

        return super().get_context_data(**kwargs)


class AboutPageView(TemplateView):

    template_name = 'pages/about.html'

    def get_context_data(self, **kwargs):
        kwargs['projects_triptych'] = Project.objects.all().order_by('-created')[0:3]

        return super().get_context_data(**kwargs)

unlabel_app/unlabel_backend/views.py
from django.views.generic import DetailView, ListView

from .models import Project, ProjectImage


class ProjectListView(ListView):
    model = Project
    
    template_name = 'projects/projects_list.html'

    def get_context_data(self, **kwargs):
        kwargs['projects'] = Project.objects.all().order_by('title')

        kwargs['results_obj'] = Project.objects.all()

        kwargs['projects_triptych'] = Project.objects.all().order_by('-created')[0:3]

        return super().get_context_data(**kwargs)


class ProjectDetailView(DetailView):
    model = Project
    
    template_name = 'projects/project_detail.html'

    def get_context_data(self, **kwargs):
        kwargs['project'] = self.get_object()

        kwargs['project_images'] = ProjectImage.objects.filter(project=self.get_object())

        kwargs['projects_triptych'] = Project.objects.exclude(title=self.get_object().title).order_by('-created')[0:3]

        return super().get_context_data(**kwargs)

unlabel_app/templates/global/base.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="{{ LANGUAGE_CODE|default:"en" }}" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="{{ LANGUAGE_CODE|default:"en" }}" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="{{ LANGUAGE_CODE|default:"en" }}" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="{{ LANGUAGE_CODE|default:"en" }}" class="no-js is-smooth-scroll-compatible"> <!--<![endif]-->
    <head>
        <title>{% block title %}{{ site.name }}{% endblock %}</title>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="created" content="{% now "jS M Y h:i" %}" />
        <meta name="description" content="{% block meta_description %}Unlabel is a studio focused on driving growth, forging creative partnerships &amp; providing innovative technology solutions for creative individuals + lifestyle &amp; fashion brands.{% endblock %}" />
        <meta name="viewport" content="{% block viewport %}width=device-width{% endblock %}" />
        <meta name="robots" content="NOARCHIVE,NOCACHE" />

        <meta name="device-size" content="set via css through font-family prop in order to be read by js">

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        {% block favicon %}
            <link rel="apple-touch-icon" sizes="57x57" href="{% static "dist/img/favicon/apple-icon-57x57.png" %}">
            <link rel="apple-touch-icon" sizes="60x60" href="{% static "dist/img/favicon/apple-icon-60x60.png" %}">
            <link rel="apple-touch-icon" sizes="72x72" href="{% static "dist/img/favicon/apple-icon-72x72.png" %}">
            <link rel="apple-touch-icon" sizes="76x76" href="{% static "dist/img/favicon/apple-icon-76x76.png" %}">
            <link rel="apple-touch-icon" sizes="120x120" href="{% static "dist/img/favicon/apple-icon-120x120.png" %}">
            <link rel="apple-touch-icon" sizes="144x144" href="{% static "dist/img/favicon/apple-icon-144x144.png" %}">
            <link rel="apple-touch-icon" sizes="152x152" href="{% static "dist/img/favicon/apple-icon-152x152.png" %}">
            <link rel="apple-touch-icon" sizes="180x180" href="{% static "dist/img/favicon/apple-icon-180x180.png" %}">
            <link rel="shortcut icon" type="image/png" href="{% static "dist/img/favicon/apple-icon-144x144.png" %}">
        {% endblock %}

        {# Block where global CSS will go. #}
        {% block styles %}{% endblock %}

        {# Additional CSS - specific to certain pages #}
        {% block extrastyles %}{% endblock %}


        {% block extrahead %}{% endblock %}
        {% block social_meta_tags %}{% endblock %}

        {% block tracking %}
            {# Default to using Google analytics #}
            {% include "partials/google_analytics.html" %}
        {% endblock %}

        <script src="{% static 'dist/js/vendors/modernizr-custom.min.js' %}"></script>
    </head>

    <body id="{% block body_id %}{% endblock %}" class="{% block body_class %}{% endblock %}">

        <!-- // page loading -->
        <div class="preloader">
            <div class="preloader-wrap">
                <div class="preloader-elements">
                    <div class="preloader-logo">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                             width="100px" height="60px" viewBox="0 0 35.5 35.5" enable-background="new 0 0 35.5 35.5" xml:space="preserve">
                        <path fill="#010101" d="M17.7,0C7.9,0,0,7.9,0,17.7c0,9.8,7.9,17.7,17.7,17.7c9.8,0,17.7-7.9,17.7-17.7C35.5,7.9,27.5,0,17.7,0z
                             M27.9,23.9h-8v-6.1l-8.6,9.7l-1.9-1.6l3.2-3.9C10,22,7.9,20.5,7.9,17.6v-6.6h3v6.6c0,1.3,0.7,2,2,2c1.3,0,2-0.7,2-2v-6.6h3v5.4
                            L25,8l2,1.6l-4.1,4.8v7.6h5V23.9z"/>
                        </svg>
                    </div>
                    <p class="preloader-text">
                        <span class="u-block">Style, Introduced.</span>
                        <span id="progstat" class="u-block">00</span>
                    </p>
                </div> 
            </div>
        </div>
        <!--// page loading -->

        <!-- // page sweeper -->
        <div class="page-sweeper"></div>
        <!-- // page sweeper -->
       
        
        {# Main content goes in this 'layout' block #}
        {% block layout %}{% endblock %}

        {# Scripts loaded from a CDN. #}
        {% block cdn_scripts %}
            <!-- jQuery -->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
        {% endblock %}

        {# Local scripts #}
        {% block scripts %}
            {% if debug %}
                <script src="{% static 'dist/js/bundle.js' %}"></script>
            {% else %}
                <script src="{% static 'dist/js/bundle.min.js' %}"></script>
            {% endif %}
        {% endblock %}

        {# Additional JS scripts #}
        {% block extrascripts %}{% endblock %}
    </body>
</html>

unlabel_app/templates/global/layout_2_col.html
{% extends "global/layout.html" %}

{% block content_wrapper %}

<main id="content_inner" class="{% block content_classnames %}{% endblock %}">

    {% block before_layout %}{% endblock %}

    <div class="grid {% block layout_extra_classnames %}{% endblock %}">
        <div class="grid__sidebar {% block layout_sidebar_extra_classnames %}{% endblock %}" {% block layout_sidebar_extra_style %}{% endblock %}>
            {% block column_left %}{% endblock %}
        </div>
        {% block grid %}
        <div class="grid__main">
            <div class="grid__banner">{% block grid_banner %}{% endblock %}</div>
            {% block grid_header %}
            <div class="grid__header">
                {% block grid_header_title %}
                    <div class="grid__headerTitle">{% block grid_header_titleContent %}{% endblock %}</div>
                {% endblock %}
                <div class="grid__headerNav">
                    <div class="grid__headerNavGroup">
                        {% block grid_header_filters %}{% endblock %}
                    </div>
                    <div class="grid__headerNavGroup">
                        {% block grid_header_sortBy %}{% endblock %}
                        {% block grid_header_results %}{% endblock %}
                    </div>
                </div>
            </div>
            {% endblock %}

            
            <div class="grid__content">{% block content %}{% endblock %}</div>
           
        </div>
        {% endblock grid %}
    </div>

    {% block after_layout %}{% endblock %}

</main>

{% endblock %}

unlabel_app/templates/pages/home.html
{% extends "global/layout.html" %}

{% load i18n %}
{% load static %}
{% load cloudinary %}

{% block title %}
    {% trans 'Style, Introduced.' %} | {{ block.super }}
{% endblock %}

{% block body_id %}homepage{% endblock %}
{% block body_class %}homepage{% endblock %}

{% block content %}
    <section class="about"> 
        <div class="container container--m-pad">
            <div class="about__header">
                <div class="about__titleContainer js-scroll" data-speed="1">
                    <h2 class="title title--caps title--destructured">
                        <span class="u-block">He-</span>
                        <span class="u-block">llo.</span>
                    </h2>
                </div>
                <div class="about__descContainer">
                    <p class="desc">{% trans 'Unlabel began with a love for fashion, design, and authentic online experiences for fashion lovers. Originally inspired by the diverse fashion scenes of NYC and Los Angeles, Unlabel grew into a multi-disciplinary studio. We believe in introducing a sense of style in everything that we do.' %}</p>
                </div>
            </div>

            <div class="about__story">
                <div class="about__storyDesc js-scroll" data-speed="1"></div>
                <div class="about__storyVisual js-scroll" data-speed="-1">
                    {% if debug %}
                        <img src="{% static 'dist/img/temp/homepage-visual.jpg' %}" alt="Unlabel Homepage Visual" />
                    {% else %}
                        <img src="https://res.cloudinary.com/hqz2myoz0/image/upload/c_fit,q_auto,w_1000/v1539284188/homepage-visual_dma5pk.jpg" alt="Unlabel Story Visual" />
                    {% endif %} 
                </div>
            </div>
        </div>
    </section>

    <section class="home__creators color-context color-context--creators">
        <div class="home__CreatorsBg js-scroll js-scroll-mask js-scroll-mask-right"></div>

        <div class="container">
            <div class="home__creatorsCols">
                <div class="home__creatorsCol home__creatorsCol--left">
                    <article class="home_creatorGridItem">
                        <figure>
                            <div class="img-container img-container--portrait">
                                {% if debug %}
                                     <img src="{% static 'dist/img/temp/tech.jpg' %}" alt="Unlabel Technology" />
                                {% else %}
                                    <img src="https://res.cloudinary.com/hqz2myoz0/image/upload/c_fit,q_auto,w_1000/v1539284187/tech_cwzzgq.jpg" alt="Unlabel Technology" />
                                {% endif %}
                               
                            </div>
                            <figcaption>
                                <h3>{% trans 'We help you build your dream product' %}</h3>
                                <p><small>{% trans 'Technology' %}</small></p>
                            </figcaption>
                        </figure>
                    </article>
                    <div class="home__creatorsTitleContainer">
                        <h2 class="title title--caps">{% trans 'Our<br> Studio' %}</h2>
                    </div>
                    <div class="home__creatorsCtaContainer">
                        <a class="cta cta--dark" href="{% url 'about' %}">{% trans 'Discover Unlabel' %}</a>
                    </div>
                    <!-- <div class="home__creatorsSubtitleContainer">
                        <div class="subtitle subtitle--medium home_creatorGridItem">{% trans 'Every project is completed with quality, style and uniqueness.' %}</div>
                    </div> -->
                </div>
                
                <div class="home__creatorsCol home__creatorsCol--middle js-scroll" data-speed='2'>
                    <article class="home_creatorGridItem">
                        <figure>
                            <div class="img-container img-container--portrait">
                                {% if debug %}
                                     <img src="{% static 'dist/img/temp/design.jpg' %}" alt="Unlabel Design" />
                                {% else %}
                                    <img src="https://res.cloudinary.com/hqz2myoz0/image/upload/c_fit,q_auto,w_1000/v1539284179/design_fxd5pt.jpg" alt="Unlabel Design" />
                                {% endif %}
                            </div>
                            <figcaption>
                                <h3>{% trans 'We design to engage and delight your customers' %}</h3>
                                <p><small>{% trans 'Design' %}</small></p>
                            </figcaption>
                        </figure>
                    </article>
                </div>
                <div class="home__creatorsCol home__creatorsCol--right u-desktop-only">
                    <article class="home_creatorGridItem">
                        <figure>
                            <div class="img-container img-container--portrait">
                                {% if debug %}
                                     <img src="{% static 'dist/img/temp/influence.jpg' %}" alt="Unlabel Influence" />
                                {% else %}
                                    <img src="https://res.cloudinary.com/hqz2myoz0/image/upload/c_fit,q_auto,w_1000/v1539284187/influence_haekie.jpg" alt="Unlabel Influence" />
                                {% endif %}
                            </div>
                            <figcaption>
                                <h3>{% trans 'We help you get the word out about your brand' %}</h3>
                                <p><small>{% trans 'Influence' %}</small></p>
                            </figcaption>
                        </figure>
                    </article>
                    <article class="home_creatorGridItem">
                        <figure>
                            <div class="img-container img-container--portrait">
                                {% if debug %}
                                    <img src="{% static 'dist/img/temp/content.jpg' %}" alt="Unlabel Content" />
                                {% else %}
                                    <img src="https://res.cloudinary.com/hqz2myoz0/image/upload/c_fit,q_auto,w_1000/v1539284180/content_rkopt2.jpg" alt="Unlabel Content" />
                                {% endif %}
                            </div>
                            <figcaption>
                                <h3>{% trans 'We create content that keeps your customers coming back for more' %}</h3>
                                <p><small>{% trans 'Content' %}</small></p>
                            </figcaption>
                        </figure>
                    </article>
                </div>
            </div>
        </div>
    </section>
   
    <section class="home__brands color-context color-context--brands">
        <div class="container">
            <h2 class="home__brandsTitle title title--caps">{% trans 'Our<br class="u-desktop-only"/> Projects' %}</h2>

            <div class="home__brandsCarousel carousel">
                <div class="cols cols--m cols--align-left cols--align-top">
                    <div class="col brands__carouselColLeft">
                        <div class="swiper-container carousel_visualsSlider home__brandsVisualsSlider">
                            <div class="swiper-wrapper">
                                {% for project in projects %}
                                    <div class="swiper-slide">
                                        <div class="visual visual--landscape js-scroll js-scroll-mask js-scroll-mask-right">
                                            <img src="{% cloudinary_url project.cover_image GENERAL_IMAGES %}" alt="{{ project.title }}">
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="col brands__carouselColRight">
                        <div class="swiper-container carousel__backgroundsSlider home__brandsBgsSlider">
                            <div class="swiper-wrapper">
                                {% for project in projects %}
                                    <div class="swiper-slide">
                                        <div class="carousel__bgSlide" style="background-color: {% cycle '#EDDDDD' '#DEEDEE' '#DDE0ED' '#F5E5D9' %};"></div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="home__brandsCarouselContentWrapper">
                            <div class="swiper-container carousel_contentsSlider home__brandsContentsSlider">
                                <div class="swiper-wrapper">
                                    {% for project in projects %}
                                        <div class="swiper-slide">
                                            <h3 class="carousel_contentItem subtitle">{{ project.title }}</h3>
                                            <div class="carousel__contentItem desc desc--small">
                                                <!-- {{ project.description|truncatechars:500|safe }}<br><br> -->
                                                <a class="link" href="{% url 'projects:project_detail' project.slug %}">View Project</a></div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="home__brandsCarouselNav">
                                <a class="carousel__btn carousel__btn--prev" href="#prev"><span class="fonticon fonticon--smallBox fonticon--carouselArrowLeft"></span></a><a class="carousel__btn carousel__btn--next" href="#next"><span class="fonticon fonticon--smallBox fonticon--carouselArrowRight"></span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <nav class="home__brandsNav">
                <ul class="home__brandsNavList">
                    <li class="home__brandsNavItem">
                        <a href="{% url 'projects:projects' %}" class="cta cta--dark">{% trans 'View All Projects' %}</a>
                    </li>
                </ul>
            </nav>

        </div>
    </section>

    <section class="about__footer" style="margin: 50px 0;">
        <div class="logo">
            <span class="logo__icon">
                <img src="{% static 'dist/img/logo_full.svg' %}" alt="Unlabel Logo">
            </span>
        </div>
        <h2 class="title title--small">{% trans "Style, Introduced." %}</h2>
    </section>
{% endblock %}

unlabel_app/templates/partials/extrascripts.html
{% comment %}
    This file exists so you can easily add your own Javascript without
    having to fork layout.html etc. Instead, just override this file.
{% endcomment %}

unlabel_app/templates/partials/footer.html
{% load i18n %}
{% load staticfiles %}

<footer class="footer">
    <div class="footer__bar footer__bar--top">
        <nav class="footer__nav footer__nav--primary">
            <a class="footer__home" href="{% url 'home' %}" title="{% trans 'Home' %}">
                <div class="logo">
                    <span class="logo__label">{% block brand_title %}Unlabel <small>Style, Introduced.</small>{% endblock %}</span>
                    <span class="logo__icon">
                        <img src="{% static 'dist/img/logo_light.svg' %}" alt="Unlabel Logo">
                    </span>
                </div>
            </a>
            <ul class="footer__navList">
                <li>
                    <a class="link link--thick link--discrete" href="/">{% trans 'Home' %}</a>
                </li>
                <li>
                    <a class="link link--thick link--discrete" href="{% url 'about' %}">{% trans 'About' %}</a>
                </li>
                <li>
                    <a class="link link--thick link--discrete" href="{% url 'projects:projects' %}">{% trans 'Projects' %}</a>
                </li>
                <li>
                    <a class="link link--thick link--discrete" href="{% url 'contact' %}">{% trans 'Contact' %}</a>
                </li>
            </ul>
        </nav>
    </div>
    <div class="footer__bar footer__bar--bottom cols cols--align-middle">
        <div class="footer__copyright"><span class="footer__copyrightSymbol">©</span>{% now 'Y' %} {% trans 'Unlabel. All rights reserved' %}</div>
        <nav class="footer__nav footer__nav--secondary">
            <!-- <ul class="footer__navList footer__navList--legal">
                <li>
                    <a href="" title="">{% trans 'info@unlabel.us' %}</a>
                </li>
            </ul> -->
            <!-- <ul class="footer__navList footer__navList--social">
                <li>
                    <a href="https://www.instagram.com/unlabel_us/" target="_blank" title="{% trans 'Instagram' %}"><span class="fonticon fonticon--instagram fonticon--smallBox"></span></a>
                </li>
            </ul> -->
        </nav>
    </div>
</footer>

unlabel_app/templates/partials/google_analytics.html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-121345121-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-121345121-1');
</script>

unlabel_app/templates/partials/header.html
{% load i18n %}
{% load staticfiles %}

<header class="header">
    <div id="header-submenu-overlay" class="header__overlay"></div>
    <div class="header__bar cols cols--align-middle">
        <nav class="header__nav header__nav--primary nav--inline">
            <a href="{% url 'home' %}" title="{% trans 'Home' %}">
                <div class="logo">
                    <span class="logo__label">{% block brand_title %}{% trans 'Unlabel' %}<small>{% trans 'Style, Introduced' %}</small>{% endblock %}</span>
                    <span class="logo__icon">
                        <img src="{% static 'dist/img/logo_dark.svg' %}" alt="Unlabel Logo">
                    </span>
                </div>
            </a>
            <ul class="header__navList nav__list u-desktop-only">
                <li class="header__navListItem">
                    <a class="link link--thick link--discrete" href="/">{% trans 'Home' %}</a>
                </li>
                <li class="header__navListItem">
                    <a class="link link--thick link--discrete" href="{% url 'about' %}">{% trans 'About' %}</a>
                </li>
                <li class="header__navListItem">
                    <a class="link link--thick link--discrete" href="{% url 'projects:projects' %}">{% trans 'Projects' %}</a>
                </li>
                <li class="header__navListItem">
                    <a class="link link--thick link--discrete" href="{% url 'contact' %}">{% trans 'Contact' %}</a>
                </li>
            </ul>
        </nav>
        <nav class="header__nav header__nav--secondary nav--inline">
            <a class="burgerMenu u-mobile-only" href="#mobile-main-nav" title="{% trans 'Toggle Menu' %}">
                <span class="burgerMenu__bar burgerMenu__bar--top"></span>
                <span class="burgerMenu__bar burgerMenu__bar--middle"></span>
                <span class="burgerMenu__bar burgerMenu__bar--bottom"></span>
            </a>
        </nav>
        <div class="drawer drawer--right" id="mobile-main-nav">
            <a href="#close-drawer" class="drawer__backdrop" title="{% trans 'Close Menu' %}"></a>
            <div class="drawer__frame">
                <div class="drawer__header drawer__header--bar">
                    <div class="drawer__headerContent"></div>
                    <a href="#close-drawer" class="drawer__close close" title="{% trans 'Close Menu' %}"></a>
                </div>
                <div class="drawer__scroller">
                    <div class="drawer__content">
                        <ul class="drawer__list">
                            <li class="drawer__item">
                                <a class="drawer__link drawer__link--large" href="/">
                                    <span class="drawer__linkLabel">{% trans 'Home' %}</span>
                                    <span class="fonticon fonticon--smallBox fonticon--carouselArrowRight"></span>
                                </a>
                            </li>
                            <li class="drawer__item">
                                <a class="drawer__link drawer__link--large" href="{% url 'about' %}">
                                    <span class="drawer__linkLabel">{% trans 'About' %}</span>
                                    <span class="fonticon fonticon--smallBox fonticon--carouselArrowRight"></span>
                                </a>
                            </li>
                            <li class="drawer__item">
                                <a class="drawer__link drawer__link--large" href="{% url 'projects:projects' %}" title="{% trans 'Projects' %}">
                                    <span class="drawer__linkLabel">{% trans 'Projects' %}</span>
                                    <span class="fonticon fonticon--smallBox fonticon--carouselArrowRight"></span>
                                </a>
                            </li>
                            <li class="drawer__item">
                                <a class="drawer__link drawer__link--large" href="{% url 'contact' %}" title="{% trans 'Contact' %}">
                                    <span class="drawer__linkLabel">{% trans 'Contact' %}</span>
                                    <span class="fonticon fonticon--smallBox fonticon--carouselArrowRight"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="drawer__footer">
                        <div class="drawer__branding">
                            <a href="{% url 'home' %}" title="{% trans 'Home' %}">
                                <div class="logo">
                                    <span class="logo__label">Unlabel</span>
                                    <span class="logo__icon">
                                        <img src="{% static 'dist/img/logo_dark.svg' %}" alt="Unlabel Logo">
                                    </span>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>